names:
  '0': persona
  '1': pantalla
  '2': teclado
  '3': mouse
  '4': mano
  '5': monitor
  '6': telefono
nc: 7
path: E:\ProyectoIA\data\processed
train: images/train/programador
val: images/train/programador
