names:
  '0': persona
  '1': pantalla
  '2': teclado
  '3': monitor
  '4': mouse
  '5': telefono
nc: 6
path: C:\Users\JoseusZThinkPad\Downloads\ProyectoIA\data\processed
train: images/train/programador
val: images/train/programador
