names:
  '0': persona
  '1': teclado
  '2': mano
  '3': monitor
  '4': mouse
  '5': puntero
  '6': computadora
  '7': telefono
nc: 8
path: E:\ProyectoIA\data\processed
train: images/train/smart
val: images/train/smart
  