# Dataset configuration for Taqueria Project
path: C:/Users/JoseusZ/Desktop/ProyectoTaqueria/data
train: processed/images/train
val: processed/images/val

# Number of classes
nc: 6

# Class names
names: 
  0: persona
  1: tortilla
  2: carne
  3: cebolla
  4: cilantro
  5: salsa