activities:
  '0': persona
  '1': teclado
  '2': mano
  '3': monitor
  '4': mouse
  '5': puntero
  '6': computadora
  '7': telefono
metrics:
- tiempo_activo
- cambios_actividad
- eficiencia_trabajo
- tiempo_herramientas
project_name: analisis_productividad
training:
  base_model: yolov8n.pt
  batch_size: 4
  epochs: 50
  image_size: 416
work_type: programador
