activities:
  '0': persona
  '1': monitor
  '2': teclado
  '3': mouse
  '4': mano
  '5': laptop
  '6': telefono
mediapipe_modules:
- hands
- pose
metrics:
- tiempo_activo
- cambios_actividad
- eficiencia_trabajo
- tiempo_herramientas
project_name: analisis_programador
training:
  base_model: yolov8n.pt
  batch_size: 16
  epochs: 1000
  image_size: 416
  patience: 20
work_type: programador
